version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - '@babel/*'
          - '@types/*'
          - 'eslint*'
          - 'webpack*'
        update-types:
          - 'minor'
          - 'patch'
